//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlitzhomeOrder
    {
        public string orderid { get; set; }
        public string clientpo { get; set; }
        public string shipping_instructions { get; set; }
        public string comments { get; set; }
        public string start_ship_date_value { get; set; }
        public string orddate { get; set; }
        public string ship_complete { get; set; }
        public string shipMethod { get; set; }
        public string alternateid { get; set; }
        public string ship2name { get; set; }
        public string ship2attention { get; set; }
        public string ship2address1 { get; set; }
        public string ship2address2 { get; set; }
        public string ship2address3 { get; set; }
        public string ship2city { get; set; }
        public string ship2state { get; set; }
        public string ship2zip { get; set; }
        public string ship2country { get; set; }
        public string ship2isresidential { get; set; }
        public string ship2phone { get; set; }
        public string ship2email { get; set; }
        public string carrier { get; set; }
        public string weight { get; set; }
        public string num_boxes { get; set; }
        public string length { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string pakage_type { get; set; }
        public string billingoption { get; set; }
        public string ref1 { get; set; }
        public string ref2 { get; set; }
        public string ref3 { get; set; }
        public string ref4 { get; set; }
        public string ref5 { get; set; }
        public string ref6 { get; set; }
        public string tp_accnt { get; set; }
        public string billAddr1 { get; set; }
        public string billAddr2 { get; set; }
        public string billname { get; set; }
        public string billAttention { get; set; }
        public string billCity { get; set; }
        public string billCountry { get; set; }
        public string billPhone { get; set; }
        public string billState { get; set; }
        public string billZip { get; set; }
        public string fromadd1 { get; set; }
        public string fromcity { get; set; }
        public string fromstate { get; set; }
        public string fromzip { get; set; }
        public string skued { get; set; }
        public string clientskued { get; set; }
        public string qtyed { get; set; }
        public string alt_nameed { get; set; }
        public string descriptioned { get; set; }
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
